"""add image_job, plan and quota_policy tables

Revision ID: 6f18ba5e848e
Revises: ced652350042
Create Date: 2025-07-26 15:22:26.037694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db


# revision identifiers, used by Alembic.
revision: str = '6f18ba5e848e'
down_revision: Union[str, None] = 'ced652350042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False, default=0),
    sa.Column('image_credits', sa.Integer(), nullable=False, default=0),
    sa.Column('video_credits', sa.Integer(), nullable=False, default=0),
    sa.Column('plan_type', sa.Enum('subscription', 'package', 'topup', 'custom', name='plan_type_enum'), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_job',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='image_job_status_enum'), nullable=False),
    sa.Column('replicate_id', sa.String(), nullable=True),
    sa.Column('output_url', sa.Text(), nullable=True),
    sa.Column('predict_time', sa.Float(), nullable=True),
    sa.Column('usd_cost', sa.Float(), nullable=True),
    sa.Column('credits_spent', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('completed_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('replicate_id')
    )
    op.create_table('quota_policy',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('resource_pattern', sa.String(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('window', sa.String(), nullable=False),
    sa.Column('effective_from', sa.BigInteger(), nullable=True),
    sa.Column('expires_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quota_policy')
    op.drop_table('image_job')
    op.drop_table('plan')
    # ### end Alembic commands ###