"""add payment_order_audit table

Revision ID: add_payment_order_audit
Revises: b539b26ab39d
Create Date: 2025-01-10 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'add_payment_order_audit'
down_revision: Union[str, None] = 'b539b26ab39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_order_audit',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),  # 'confirm', 'decline', 'create'
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('actor_email', sa.String(), nullable=True),
    sa.Column('actor_name', sa.String(), nullable=True),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('audit_metadata', sa.JSON(), nullable=True),  # ✅ Fixed: changed from 'metadata' to 'audit_metadata'
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['order_id'], ['payment_order.order_id'], ),
    )
    # Create index for faster queries
    op.create_index('idx_payment_order_audit_order_id', 'payment_order_audit', ['order_id'])
    op.create_index('idx_payment_order_audit_actor_id', 'payment_order_audit', ['actor_id'])
    op.create_index('idx_payment_order_audit_action', 'payment_order_audit', ['action'])
    op.create_index('idx_payment_order_audit_created_at', 'payment_order_audit', ['created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payment_order_audit_created_at', table_name='payment_order_audit')
    op.drop_index('idx_payment_order_audit_action', table_name='payment_order_audit')
    op.drop_index('idx_payment_order_audit_actor_id', table_name='payment_order_audit')
    op.drop_index('idx_payment_order_audit_order_id', table_name='payment_order_audit')
    op.drop_table('payment_order_audit')
    # ### end Alembic commands ###
