"""add 3 billing tables

Revision ID: b539b26ab39d
Revises: 9f0c9cd09105
Create Date: 2025-06-26 14:35:18.315266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.internal.db
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b539b26ab39d'
down_revision: Union[str, None] = '9f0c9cd09105'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_transaction',
    sa.Column('tx_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('delta', sa.BigInteger(), nullable=False),
    sa.Column('usd_spend', sa.Numeric(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('tx_id')
    )
    op.create_table('payment_order',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('credit', 'upgrade', 'plan_payment', name='order_type_enum'), nullable=False),
    sa.Column('plan_target', sa.Text(), nullable=True),
    sa.Column('plan_id', sa.Enum('starter', 'pro', 'studio', name='plan_enum'), nullable=True),
    sa.Column('credits', sa.BigInteger(), nullable=True),
    sa.Column('amount_mmk', sa.Numeric(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'failed', name='payment_status_enum'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('paid_at', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('user_credit',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.Enum('starter', 'pro', 'studio', name='plan_enum'), nullable=False),
    sa.Column('credit_balance', sa.BigInteger(), nullable=False),
    sa.Column('monthly_quota', sa.BigInteger(), nullable=False),
    sa.Column('current_period_end', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'grace', 'expired', name='status_enum'), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_credit')
    op.drop_table('payment_order')
    op.drop_table('credit_transaction')
    # ### end Alembic commands ###
