name: Build and Deploy to Coolify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/open-webui:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/open-webui:latest

      - name: Trigger Coolify redeploy
        run: |
          curl '${{ secrets.COOLIFY_DEPLOY_HOOK }}' \
            --header 'Authorization: Bearer ${{ secrets.COOLIFY_API_KEY }}'
